### ISSUE TITLE
Bluefog didn't throw an error when CUDA memory is not enough.

### ISSUE THREAD

**Issue by hanbinhu** [Bluefog-Lib/bluefog#32]
When CUDA memory is not enough, horovod will throw the following exception
`RuntimeError: CUDA error: out of memory`
However, our library will freeze and report nothing.

**Comment by Bluefog-Lib** [comment]
maybe related to issue #44

**Comment by Bluefog-Lib** [comment]
One finding is some processes silently shut down without warning while other processes keep running until collective communication ops are encountered and froze forever.

**Comment by ybc1991** [comment]
After adding negotiating stage, it should be solved
